export function renderAdminUpdateView(): string {
  return `<section id="admin-view-updates" class="admin-view update-view" aria-labelledby="update-title" hidden>
  <div class="update-heading"><div><p class="eyebrow">System Release</p><h2 id="update-title">版本与更新</h2></div><button id="check-updates" class="button secondary" type="button">重新检查</button></div>
  <p id="update-connection" class="update-connection muted" role="status" aria-live="polite">正在读取服务器版本状态…</p>
  <div class="release-grid">
    <section class="release-card" aria-labelledby="current-release-title"><p class="release-label">当前版本</p><h3 id="current-release-title">—</h3><p id="current-release-meta" class="release-meta">等待服务器确认</p><span id="current-release-health" class="health-badge">状态未知</span></section>
    <section class="release-card candidate-card" aria-labelledby="candidate-release-title"><p class="release-label">稳定版候选</p><h3 id="candidate-release-title">—</h3><p id="candidate-release-meta" class="release-meta">尚未检查</p><ul id="candidate-summary" class="release-summary"></ul><p id="candidate-compatibility" class="compatibility"></p><a id="candidate-release-link" class="release-link" href="#" target="_blank" rel="noopener noreferrer" hidden>查看完整发布说明</a><button id="install-update" class="button update-action" type="button" hidden>安装更新</button></section>
  </div>
  <section class="update-task" aria-labelledby="update-task-title"><div class="task-heading"><div><p class="release-label">更新任务</p><h3 id="update-task-title">没有进行中的任务</h3></div><span id="update-task-state" class="task-state">空闲</span></div><p id="update-task-message" class="task-message muted">发现新版本后，可由管理员手动确认安装。</p><ol id="update-timeline" class="update-timeline" hidden>
    <li data-update-stage="verifying_release"><span></span><div><strong>校验版本</strong><small>确认正式 Release 与制品可信</small></div></li>
    <li data-update-stage="pulling_artifacts"><span></span><div><strong>获取制品</strong><small>下载固定摘要的应用镜像</small></div></li>
    <li data-update-stage="staging_release"><span></span><div><strong>准备版本</strong><small>创建不可变发布目录并校验配置</small></div></li>
    <li data-update-stage="rehearsing_migration"><span></span><div><strong>迁移演练</strong><small>在隔离数据副本中验证候选版本</small></div></li>
    <li data-update-stage="backing_up"><span></span><div><strong>备份门禁数据</strong><small>切换前完成在线备份与完整性检查</small></div></li>
    <li data-update-stage="ready_to_switch"><span></span><div><strong>等待切换</strong><small>所有切换前门禁已通过</small></div></li>
    <li data-update-stage="switching"><span></span><div><strong>切换服务</strong><small>管理入口可能短暂重连</small></div></li>
    <li data-update-stage="verifying_loopback"><span></span><div><strong>验证容器</strong><small>检查版本、数据库与回环健康</small></div></li>
    <li data-update-stage="verifying_origin"><span></span><div><strong>验证源站</strong><small>确认 OpenResty 与源站边界</small></div></li>
    <li data-update-stage="verifying_public"><span></span><div><strong>验证公网</strong><small>确认 HTTPS 与访问控制正常</small></div></li>
    <li data-update-stage="rolling_back"><span></span><div><strong>恢复旧版本</strong><small>候选版本未通过门禁，正在自动恢复</small></div></li>
  </ol></section>
  <p id="update-feedback" class="update-feedback" role="alert" hidden></p>
  <section class="update-history" aria-labelledby="update-history-title"><div class="history-heading"><h3 id="update-history-title">更新记录</h3><button id="refresh-history" class="text-button" type="button">刷新</button></div><div id="update-history-list" class="history-list"><p class="muted">尚无更新记录</p></div></section>
  <dialog id="update-confirm" class="update-confirm"><form method="dialog"><p class="eyebrow">Manual Release</p><h3 id="update-confirm-title">确认安装</h3><p id="update-confirm-copy" class="muted"></p><dl class="preflight-list"><div><dt>发布来源</dt><dd id="preflight-source">正在校验</dd></div><div><dt>数据库兼容</dt><dd id="preflight-database">正在校验</dd></div><div><dt>并发任务</dt><dd id="preflight-lock">正在校验</dd></div></dl><div class="confirm-actions"><button id="cancel-update" class="button secondary" value="cancel">稍后处理</button><button id="confirm-update" class="button" type="button" disabled>开始更新</button></div></form></dialog>
</section>`;
}

export const adminUpdateStyles = `
  .admin-nav{display:flex;align-items:center;gap:2px;margin-top:20px;border-bottom:1px solid #423c33}.nav-button{position:relative;min-height:44px;border:0;border-bottom:2px solid transparent;background:transparent;color:#9e9588;padding:0 16px}.nav-button[aria-selected="true"]{border-color:#d9973e;color:#f0eadf}.update-dot{position:absolute;right:6px;top:9px;width:6px;height:6px;border-radius:50%;background:#d9973e}
  .admin-view[hidden]{display:none}.update-view{padding-top:30px}.update-heading,.task-heading,.history-heading{display:flex;align-items:center;justify-content:space-between;gap:18px}.update-heading h2,.task-heading h3,.history-heading h3{margin:4px 0 0}.update-connection{min-height:22px;margin:12px 0 18px;font-size:12px}.release-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1.35fr);border-top:1px solid #423c33;border-bottom:1px solid #423c33}.release-card{min-width:0;padding:24px 24px 26px 0}.candidate-card{border-left:1px solid #423c33;padding-left:24px}.release-label{margin:0;color:#92897c;font-size:11px;text-transform:uppercase}.release-card h3{margin:8px 0 4px;font:500 28px/1.2 "Songti SC","STSong",serif}.release-meta,.compatibility{margin:0;color:#aaa194;font-size:12px;line-height:1.7}.health-badge,.task-state{display:inline-flex;align-items:center;min-height:28px;margin-top:18px;border-left:2px solid #777;padding:0 9px;color:#bbb2a5;font-size:12px}.health-badge.healthy,.task-state.succeeded{border-color:#668773;color:#9ac4aa}.health-badge.unhealthy,.task-state.failed{border-color:#a85f51;color:#e4a298}.release-summary{display:grid;gap:8px;margin:18px 0 14px;padding:0;list-style:none}.release-summary li{display:grid;grid-template-columns:auto minmax(0,1fr);gap:9px;font-size:13px;line-height:1.65}.summary-kind{color:#d9a057;font-size:11px}.compatibility{border-top:1px solid #302c26;padding-top:12px}.release-link{display:inline-block;margin-top:12px;color:#dca45a;font-size:12px}.update-action{width:100%;margin-top:20px}
  .update-task{padding:30px 0;border-bottom:1px solid #423c33}.task-state{margin-top:0}.task-message{margin:12px 0 0;line-height:1.7}.update-timeline{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 30px;margin:24px 0 0;padding:0;list-style:none}.update-timeline li{position:relative;display:grid;grid-template-columns:16px minmax(0,1fr);gap:11px;min-height:60px;color:#766f65}.update-timeline li>span{width:10px;height:10px;margin-top:5px;border:1px solid #5b544a;background:#0d0c0a}.update-timeline li strong,.update-timeline li small{display:block}.update-timeline li strong{font-size:13px;font-weight:500}.update-timeline li small{margin-top:3px;font-size:11px;line-height:1.5}.update-timeline li.completed{color:#9bc1a8}.update-timeline li.completed>span{border-color:#668773;background:#668773}.update-timeline li.active{color:#f0c27d}.update-timeline li.active>span{border-color:#d9973e;background:#d9973e}.update-timeline li.failed{color:#e4a298}.update-timeline li.failed>span{border-color:#a85f51;background:#a85f51}.update-feedback{margin:18px 0 0;border-left:3px solid #a85f51;background:#21130f;color:#ffd8cc;padding:12px 14px}.update-history{padding-top:30px}.text-button{min-height:44px;border:0;background:transparent;color:#dca45a;padding:0 4px}.history-list{margin-top:12px;border-top:1px solid #423c33}.history-item{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:14px;padding:16px 0;border-bottom:1px solid #302c26}.history-item strong,.history-item small{display:block}.history-item small{margin-top:5px;color:#8e867a;font-size:11px}.history-result{align-self:start;border-left:2px solid #777;padding-left:8px;color:#aaa194;font-size:12px}.history-result.succeeded{border-color:#668773;color:#9ac4aa}.history-result.failed{border-color:#a85f51;color:#e4a298}
  .update-confirm{width:min(calc(100% - 32px),520px);border:1px solid #5c5448;border-radius:0;background:#13110e;color:#f0eadf;padding:0}.update-confirm::backdrop{background:rgba(0,0,0,.72)}.update-confirm form{padding:26px}.update-confirm h3{margin:8px 0 10px;font:500 28px/1.2 "Songti SC","STSong",serif}.preflight-list{margin:22px 0}.preflight-list div{display:grid;grid-template-columns:110px minmax(0,1fr);gap:12px;padding:10px 0;border-bottom:1px solid #302c26}.preflight-list dt{color:#8f8678;font-size:12px}.preflight-list dd{margin:0;font-size:12px;text-align:right}.confirm-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:22px}
  @media(max-width:700px){.admin-nav{overflow-x:auto}.nav-button{flex:1;white-space:nowrap}.update-heading{align-items:flex-start}.release-grid{grid-template-columns:1fr}.release-card{padding:22px 0}.candidate-card{border-top:1px solid #423c33;border-left:0;padding-left:0}.update-timeline{grid-template-columns:1fr}.task-heading{align-items:flex-start}.history-item{grid-template-columns:1fr}.update-confirm{width:100%;max-width:none;margin:auto 0 0;border-width:1px 0 0}.update-confirm form{padding:24px 20px max(24px,env(safe-area-inset-bottom))}.confirm-actions{grid-template-columns:1fr}.confirm-actions .button{width:100%}}
  @media(prefers-reduced-motion:no-preference){.update-timeline li.active>span{animation:update-pulse 1.6s ease-in-out infinite}@keyframes update-pulse{50%{box-shadow:0 0 0 5px rgba(217,151,62,.12)}}}
`;

export const adminUpdateScript = `
const updateFinalStates=new Set(["succeeded","failed_pre_switch","rolled_back","recovery_required"]);
const updateCriticalStates=new Set(["switching","verifying_loopback","verifying_origin","verifying_public","rolling_back"]);
const updateStageOrder=["verifying_release","pulling_artifacts","staging_release","rehearsing_migration","backing_up","ready_to_switch","switching","verifying_loopback","verifying_origin","verifying_public","rolling_back"];
const updateStateLabels={queued:"等待开始",verifying_release:"正在校验版本",pulling_artifacts:"正在获取制品",staging_release:"正在准备版本",rehearsing_migration:"正在演练迁移",backing_up:"正在备份门禁数据",ready_to_switch:"准备切换",switching:"正在切换服务",verifying_loopback:"正在验证容器",verifying_origin:"正在验证源站",verifying_public:"正在验证公网",rolling_back:"正在恢复旧版本",succeeded:"更新成功",failed_pre_switch:"更新已停止",rolled_back:"已恢复旧版本",recovery_required:"需要人工恢复"};
const updateErrorLabels={release_untrusted:"发布制品未通过可信校验",updater_upgrade_required:"服务器更新组件需要先维护",migration_incompatible:"数据库变更不支持一键更新",preflight_failed:"服务器预检未通过",artifact_pull_failed:"更新制品获取失败",staging_failed:"新版本准备失败",migration_rehearsal_failed:"数据库迁移演练未通过",backup_failed:"门禁数据备份失败",switch_failed:"服务切换失败",health_check_failed:"新版本健康验证失败",rollback_failed:"自动恢复未完成",interrupted:"任务被服务器中断"};
const blockedReasonLabels={release_untrusted:"该版本未通过可信校验，不能在线安装。",updater_upgrade_required:"需要先通过维护流程升级服务器更新组件。",migration_incompatible:"该版本包含不兼容的数据迁移，需要维护发布。"};
const summaryKindLabels={feature:"新功能",fix:"修复",security:"安全"};
let updateData=null,updateJob=null,updateTimer=null,updateFailures=0,pendingUpdateVersion="",updateAttemptKey=null,updateRequestBusy=false,updateStatusBusy=false;
const updateFeedback=byId("update-feedback"),installUpdateButton=byId("install-update"),updateDialog=byId("update-confirm");
function setAdminView(view,writeHash=true){const active=["invites","settings","updates"].includes(view)?view:"invites";byId("admin-view-invites").hidden=active!=="invites";byId("admin-view-settings").hidden=active!=="settings";byId("admin-view-updates").hidden=active!=="updates";document.querySelectorAll("[data-admin-view]").forEach((button)=>button.setAttribute("aria-selected",String(button.dataset.adminView===active)));if(writeHash)history.replaceState(null,"","#"+active);if(active==="updates"){refreshUpdateStatus();refreshUpdateHistory()}}
document.querySelectorAll("[data-admin-view]").forEach((button)=>button.addEventListener("click",()=>setAdminView(button.dataset.adminView)));
function shortRevision(value){return typeof value==="string"&&/^[0-9a-f]{40}$/.test(value)?value.slice(0,7):"—"}
function updateDate(value){return typeof value==="string"&&value.length>=16?value.replace("T"," ").slice(0,16)+" UTC":"—"}
function safeErrorCode(value){return typeof value==="string"&&Object.hasOwn(updateErrorLabels,value)?value:null}
function showUpdateFeedback(message){updateFeedback.textContent=message;updateFeedback.hidden=false}
function clearUpdateFeedback(){updateFeedback.hidden=true;updateFeedback.textContent=""}
async function updateFetch(url,options){const response=await fetch(url,{cache:"no-store",...options});let body=null;try{body=await response.json()}catch{}if(!response.ok){const error=new Error("update_request");error.code=body&&typeof body.error==="string"?body.error:"updater_unavailable";throw error}return body}
function renderCandidate(candidate,activeJob){const title=byId("candidate-release-title"),meta=byId("candidate-release-meta"),summary=byId("candidate-summary"),compatibility=byId("candidate-compatibility"),link=byId("candidate-release-link");summary.replaceChildren();link.hidden=true;installUpdateButton.hidden=true;if(!candidate){title.textContent="已是最新稳定版";meta.textContent="当前没有可安装的新版本";compatibility.textContent="";byId("update-nav-dot").hidden=true;return}title.textContent="v"+candidate.version;meta.textContent="发布于 "+updateDate(candidate.publishedAt)+" · "+shortRevision(candidate.revision);for(const item of candidate.summaryZh||[]){if(!item||!Object.hasOwn(summaryKindLabels,item.kind)||typeof item.text!=="string")continue;const row=document.createElement("li"),kind=document.createElement("span"),text=document.createElement("span");kind.className="summary-kind";kind.textContent=summaryKindLabels[item.kind];text.textContent=item.text;row.append(kind,text);summary.appendChild(row)}const database=candidate.database;if(database&&database.schemaFrom===database.schemaTo)compatibility.textContent="不改变门禁数据库结构，切换时可能短暂重连。";else if(database)compatibility.textContent="门禁数据库 "+database.schemaFrom+" → "+database.schemaTo+"，已声明可向后兼容。";if(typeof candidate.releaseUrl==="string"&&candidate.releaseUrl.startsWith("https://github.com/Zeno-cc/FilmFrame/releases/tag/")){link.href=candidate.releaseUrl;link.hidden=false}const blocked=candidate.blockedReason&&blockedReasonLabels[candidate.blockedReason];if(!candidate.installable||blocked){compatibility.textContent=blocked||"该版本当前不能在线安装。";byId("update-nav-dot").hidden=true;return}installUpdateButton.hidden=false;installUpdateButton.disabled=Boolean(activeJob);installUpdateButton.textContent=activeJob?"更新进行中":"更新到 "+candidate.version;byId("update-nav-dot").hidden=Boolean(activeJob)}
function failedStage(job){const mapping={release_untrusted:"verifying_release",updater_upgrade_required:"verifying_release",migration_incompatible:"verifying_release",preflight_failed:"verifying_release",artifact_pull_failed:"pulling_artifacts",staging_failed:"staging_release",migration_rehearsal_failed:"rehearsing_migration",backup_failed:"backing_up",switch_failed:"switching",health_check_failed:"verifying_loopback",rollback_failed:"switching"};return mapping[job.errorCode]||null}
function renderTimeline(job){const timeline=byId("update-timeline");timeline.hidden=false;const rollback=job.state==="rolling_back"||job.state==="rolled_back"||job.state==="recovery_required";let activeStage=updateStageOrder.includes(job.state)?job.state:failedStage(job);if(job.state==="succeeded")activeStage=null;if(rollback)activeStage="rolling_back";const failureStage=failedStage(job);const completedBoundary=rollback&&failureStage?updateStageOrder.indexOf(failureStage):activeStage?updateStageOrder.indexOf(activeStage):-1;timeline.querySelectorAll("li[data-update-stage]").forEach((row)=>{const stage=row.dataset.updateStage,index=updateStageOrder.indexOf(stage),isRollback=stage==="rolling_back";row.classList.toggle("active",isRollback&&job.state==="rolling_back"||!rollback&&stage===activeStage&&!updateFinalStates.has(job.state));row.classList.toggle("completed",job.state==="succeeded"||(!isRollback&&index<completedBoundary)||(isRollback&&job.state==="rolled_back"));row.classList.toggle("failed",job.state==="failed_pre_switch"&&stage===failureStage||job.state==="recovery_required"&&isRollback)})}
function updateDuration(job){const start=Date.parse(job.startedAt||job.createdAt),end=job.finishedAt?Date.parse(job.finishedAt):Date.now();if(!Number.isFinite(start)||!Number.isFinite(end)||end<start)return "";const seconds=Math.max(0,Math.floor((end-start)/1000));return seconds<60?seconds+" 秒":Math.floor(seconds/60)+" 分 "+String(seconds%60).padStart(2,"0")+" 秒"}
function renderJob(job){updateJob=job;const title=byId("update-task-title"),state=byId("update-task-state"),message=byId("update-task-message"),timeline=byId("update-timeline");if(!job){title.textContent="没有进行中的任务";state.textContent="空闲";state.className="task-state";message.textContent="发现新版本后，可由管理员手动确认安装。";timeline.hidden=true;timeline.querySelectorAll("li").forEach((row)=>row.className="");return}title.textContent=(job.previousVersion||"当前版本")+" → "+job.targetVersion;state.textContent=updateStateLabels[job.state]||"状态同步中";state.className="task-state"+(job.state==="succeeded"?" succeeded":updateFinalStates.has(job.state)?" failed":"");const error=safeErrorCode(job.errorCode);let copy;if(job.state==="succeeded")copy="已更新至 "+job.targetVersion+"，主站、门禁与管理入口验证通过。";else if(job.state==="rolled_back")copy=job.targetVersion+" 未通过上线门禁，已恢复到 "+(job.previousVersion||"旧版本")+"，当前网站运行正常。";else if(job.state==="recovery_required")copy="自动恢复未完成，请勿重复更新，并通过 SSH 执行紧急恢复流程。";else if(job.state==="failed_pre_switch")copy=(error?updateErrorLabels[error]+"。":"更新准备未完成。")+"生产版本没有切换。";else if(job.state==="rolling_back")copy="候选版本未通过验证，服务器正在恢复旧版本。";else if(updateCriticalStates.has(job.state))copy="服务正在切换与验证，管理入口可能短暂断开，页面会自动重连。";else copy="更新已交给服务器处理，可以安全关闭页面后稍后查看。";const duration=updateDuration(job);message.textContent=copy+(duration?" · "+(updateFinalStates.has(job.state)?"总耗时 ":"已用时 ")+duration:"");renderTimeline(job)}
function renderUpdateStatus(data,trackedJob){if(!data||!data.current)throw new Error("invalid_update_status");updateData=data;updateFailures=0;clearUpdateFeedback();byId("update-connection").textContent="最近检查 "+updateDate(data.checkedAt)+" · 更新组件 "+data.updaterVersion;byId("current-release-title").textContent="v"+data.current.version;byId("current-release-meta").textContent=shortRevision(data.current.revision)+" · 数据库 "+data.current.schemaVersion;const health=byId("current-release-health");health.textContent=data.current.healthy?"运行正常":"运行状态异常";health.className="health-badge "+(data.current.healthy?"healthy":"unhealthy");const visibleJob=trackedJob||data.activeJob||(updateJob&&updateFinalStates.has(updateJob.state)?updateJob:null);renderCandidate(data.candidate,data.activeJob);renderJob(visibleJob);scheduleUpdatePoll(visibleJob)}
function updateRetryDelay(){return Math.min(30000,2000*Math.pow(2,Math.min(updateFailures,4)))}
function scheduleUpdatePoll(job){clearTimeout(updateTimer);const delay=!job||updateFinalStates.has(job.state)?30000:updateCriticalStates.has(job.state)?2000:5000;updateTimer=setTimeout(refreshUpdateStatus,delay)}
async function refreshUpdateStatus(){if(updateStatusBusy)return;updateStatusBusy=true;clearTimeout(updateTimer);try{const trackedId=updateJob&&!updateFinalStates.has(updateJob.state)?updateJob.id:null;if(trackedId){try{const tracked=await updateFetch("/api/system-update/jobs/"+encodeURIComponent(trackedId)),job=tracked&&tracked.job;if(!job)throw new Error("invalid_update_job");renderJob(job);scheduleUpdatePoll(job);if(!updateFinalStates.has(job.state))return;const data=await updateFetch("/api/system-update");renderUpdateStatus(data,job);refreshUpdateHistory();return}catch(error){if(error&&error.code==="job_not_found")updateJob=null;else throw error}}const data=await updateFetch("/api/system-update");renderUpdateStatus(data)}catch(error){updateFailures+=1;byId("update-connection").textContent="与更新服务的连接暂时中断，正在自动重试。";if(error&&error.code==="updater_unavailable")showUpdateFeedback("服务器更新组件暂不可用，当前网站不受影响。");updateTimer=setTimeout(refreshUpdateStatus,updateRetryDelay())}finally{updateStatusBusy=false}}
async function forceUpdateCheck(){if(updateRequestBusy)return;updateRequestBusy=true;byId("check-updates").disabled=true;clearUpdateFeedback();try{const data=await updateFetch("/api/system-update/check",{method:"POST",headers:{...csrfHeaders,"Idempotency-Key":crypto.randomUUID()},body:"{}"});renderUpdateStatus(data)}catch(error){showUpdateFeedback(error&&error.code==="updater_upgrade_required"?blockedReasonLabels.updater_upgrade_required:"暂时无法检查新版本，当前版本继续正常运行。")}finally{updateRequestBusy=false;byId("check-updates").disabled=false}}
function openUpdateConfirmation(){const candidate=updateData&&updateData.candidate;if(!candidate||!candidate.installable||updateData.activeJob)return;pendingUpdateVersion=candidate.version;updateAttemptKey=crypto.randomUUID();byId("update-confirm-title").textContent="更新到 "+candidate.version;byId("update-confirm-copy").textContent="服务器会在切换前完成制品校验、迁移演练和门禁数据备份。";byId("preflight-source").textContent="可信稳定版";byId("preflight-database").textContent=candidate.database.backwardCompatible?"支持应用回滚":"需要维护发布";byId("preflight-lock").textContent="当前可更新";byId("confirm-update").disabled=false;updateDialog.showModal()}
async function confirmUpdate(){if(!pendingUpdateVersion||!updateAttemptKey||updateRequestBusy)return;updateRequestBusy=true;byId("confirm-update").disabled=true;byId("confirm-update").textContent="正在提交";clearUpdateFeedback();try{const result=await updateFetch("/api/system-update/jobs",{method:"POST",headers:{...csrfHeaders,"Idempotency-Key":updateAttemptKey},body:JSON.stringify({version:pendingUpdateVersion})});updateDialog.close();renderJob(result.job);if(updateData)renderCandidate(updateData.candidate,result.job);scheduleUpdatePoll(result.job)}catch(error){if(error&&error.code==="update_busy"){updateDialog.close();await refreshUpdateStatus()}else{showUpdateFeedback("更新任务未确认，请保持页面打开并重试。")}}finally{updateRequestBusy=false;byId("confirm-update").textContent="开始更新";if(updateDialog.open)byId("confirm-update").disabled=false}}
function historyResultClass(state){return state==="succeeded"?"succeeded":updateFinalStates.has(state)?"failed":""}
async function refreshUpdateHistory(){try{const data=await updateFetch("/api/system-update/history?limit=20"),root=byId("update-history-list");root.replaceChildren();if(!data||!Array.isArray(data.jobs)||data.jobs.length===0){const empty=document.createElement("p");empty.className="muted";empty.textContent="尚无更新记录";root.appendChild(empty);return}if(!updateJob&&data.jobs[0])renderJob(data.jobs[0]);for(const job of data.jobs){const row=document.createElement("div"),content=document.createElement("div"),title=document.createElement("strong"),meta=document.createElement("small"),result=document.createElement("span");row.className="history-item";title.textContent=(job.previousVersion||"当前版本")+" → "+job.targetVersion;const error=safeErrorCode(job.errorCode);meta.textContent=updateDate(job.createdAt)+(error?" · "+updateErrorLabels[error]:"");result.className="history-result "+historyResultClass(job.state);result.textContent=updateStateLabels[job.state]||"状态未知";content.append(title,meta);row.append(content,result);root.appendChild(row)}}catch{}}
byId("check-updates").addEventListener("click",forceUpdateCheck);byId("refresh-history").addEventListener("click",refreshUpdateHistory);installUpdateButton.addEventListener("click",openUpdateConfirmation);byId("confirm-update").addEventListener("click",confirmUpdate);byId("cancel-update").addEventListener("click",()=>{pendingUpdateVersion="";updateAttemptKey=null});
document.addEventListener("visibilitychange",()=>{if(!document.hidden)refreshUpdateStatus()});window.addEventListener("online",refreshUpdateStatus);window.addEventListener("pagehide",()=>clearTimeout(updateTimer));window.addEventListener("pageshow",()=>refreshUpdateStatus());
setAdminView(location.hash.slice(1),false);refreshUpdateStatus();`;
